### ISSUE TITLE
Plugin not working with Sketch 3.8.3

### ISSUE THREAD

**Issue by ghost** [abynim/sketchy-pies#3]
Hello! I have tried installing two times the plugin but it is not working.

I am trying to create pies but plugin just generating another blank circle without fill. Can you help, please?

**Comment by jshmllr** [comment]
Can also confirm:
`Version 39.1 (31720)`

Pies plugin incompatible still. 

**Steps:**
1. Create Circle
2. Select Layer
3. Run Sketch Pies
4. Output is simply a duplicate layer of the same circle.

**Comment by hardikpandya** [comment]
+1 to the above issues. Plugin not working.

**Comment by abynim** [comment]
Fixed. Please update and test! 👍
