### ISSUE TITLE
Plugin does not work after Update - Sketch Version 41 (35326)

### ISSUE THREAD

**Issue by newbit77** [abynim/sketchy-pies#4]
Nothing will be generated if you try to convert a circle into a pie-chart.

**Comment by Wolfr** [comment]
Yep, I have the same issue.

**Comment by jasonrincker** [comment]
@abynim First, thanks for creating this very useful plug-in. I'm in the middle of a project that I have used Sketchy-Pies to generate a few donut charts. Do you think this is a quick fix (likely to be remedied in the next day or so)? Or should I plan on creating charts manually for a while? Again, thank you for creating this. Cheers!

**Comment by abynim** [comment]
@jasonrincker Im hoping to fix this over the weekend. Sorry for the trouble :)

**Comment by abynim** [comment]
Just pushed an update with fixes for Sketch 41.

**Comment by jasonrincker** [comment]
@abynim Thank you for this plug-in, your creation is much appreciated.

If you're interested, I have a proposal for making the input UI more user-friendly.
Best wishes, 
Jason
![proposal-sketchypies-ui](https://cloud.githubusercontent.com/assets/15252887/20247629/f722d028-a98d-11e6-951d-8a50741efaa3.png)

**Comment by abynim** [comment]
@jasonrincker thanks for the suggestions. A responsive UI like the one you suggested is not supported out of the box for plugins. It's possible, but would take a lot more work. I'll keep it in mind for sometime in the future :)

**Comment by newbit77** [comment]
Thanks 4 the update! Great Work!!!!!!
